clc,clear,close all

figure
axes
view(3)
ax = gca();

angle = 0.5;
initialView = ax.View; % (-36.5,30)
angles1 = [initialView(1)*ones(1,47),...
    initialView(1):angle:-initialView(1),...
    -initialView(1)*ones(1,47),...
    -initialView(1):-angle:2*initialView(1),...
    2*initialView(1)*ones(1,47),...
    2*initialView(1):angle:initialView(1),...
    initialView(1)*ones(1,47)];
angles2 = [initialView(2):-angle:-initialView(2),...
    -initialView(2)*ones(1,47),...
    -initialView(2):angle:2*initialView(2),...
    2*initialView(2)*ones(1,47),...
    2*initialView(2):-angle:initialView(2)];
Azimuths = [angles1,initialView(1)*ones(size(angles2))];
Elevations = [initialView(2)*ones(size(angles1)),angles2];

r = 1;
x = r*sin(Elevations).*cos(Azimuths);
y = r*sin(Elevations).*sin(Azimuths);
z = r*cos(Azimuths);




